project:
  type: website

website:
  title: "blog-template"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/malaiikkkaa
format:
  html:
    title-block-banner: "#e7eaeb"
    title-block-banner-color: "#440154"
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "On this page"
    toc-depth: 3
    toc-expand: true


